version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-book
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_network
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-demo
volumes:
  mysql-data:
networks:
  spring-demo:
