spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
